version: "3.7"

volumes:
  redis-data:
  models-data:

services:
  redis:
    image: redis:alpine
    volumes:
      - "redis-data:/data"

  worker:
    image: gcharbon/pyheartex-example-worker
    environment:
      RQ_QUEUE_NAME: model_server
      REDIS_HOST: redis
      REDIS_PORT: 6379

  server:
    image: gcharbon/pyheartex-example-server
    environment:
      RQ_QUEUE_NAME: model_server
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - "models-data:/root/.heartex"
    ports:
      - 9090:9090

  labelstudio:
    image: heartexlabs/label-studio
    ports:
      # <HOST_PORT:CONTAINER_PORT>
      - 8280:8200
    command:
      - label-studio
      - init
      - labeling_project



