version: "3.7"

volumes:
  redis-data:
  models-data:
  images-data:
  labelstudio_volume:


configs:
  label_studio_config:
    file: config/config.json
  label_studio_tasks:
    file: config/tasks.json
  label_studio_labelling:
    file: config/config.xml


services:
  redis:
    image: redis:alpine
    volumes:
      - "redis-data:/data"

  worker:
    image: gcharbon/pyheartex-example-worker
    environment:
      RQ_QUEUE_NAME: model_server
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MODEL_DIR: /data/models
      IMAGE_DIR: /data/images
      LOG_LEVEL: DEBUG
      CUDA_VISIBLE_DEVICES: -1 
      # TF_CPP_MIN_LOG_LEVEL: 2
    volumes:
      - "models-data:/data/models"
      - "images-data:/data/images"

  server:
    image: gcharbon/pyheartex-example-server
    environment:
      RQ_QUEUE_NAME: model_server
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MODEL_DIR: /data/models
      IMAGE_DIR: /data/images
      LOG_LEVEL: DEBUG
      CUDA_VISIBLE_DEVICES: -1
      # TF_CPP_MIN_LOG_LEVEL: 2
    volumes:
      - "models-data:/data/models"
      - "images-data:/data/images"
    ports:
      - 9090:9090
    deploy:
      resources:
        limits:
          cpus: '0.95'
        reservations:
          cpus: '0.80'

  labelstudio:
    image: heartexlabs/label-studio
    command:
      - label-studio
      - start
      - labeling_project
      # - --init
      # - --template
      # - image_classification
      # - --ml-backend-url
      # - http://server:9090
      # - --ml-backend-name
      # - fastai_classifier
      # - labeling_project

    ports:
      # <HOST_PORT:CONTAINER_PORT>
      - 8280:8080
    volumes:
      - labelstudio_volume:/label-studio/labeling_project
    configs:
      - source: label_studio_config
        target: /label-studio/labeling_project/config.json
      - source: label_studio_tasks
        target: /label-studio/labeling_project/tasks.json
      - source: label_studio_labelling
        target: /label-studio/labeling_project/config.xml