version: "3.7"

volumes:
  redis-data:
  models-data:
  images-data:

services:
  redis:
    image: redis:alpine
    volumes:
      - "redis-data:/data"

  worker:
    image: gcharbon/pyheartex-example-worker
    environment:
      RQ_QUEUE_NAME: model_server
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MODEL_DIR: /data/models
      IMAGE_DIR: /data/images
    volumes:
      - "models-data:/data/models"
      - "images-data:/data/images"

  server:
    image: gcharbon/pyheartex-example-server
    environment:
      RQ_QUEUE_NAME: model_server
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MODEL_DIR: /data/models
      IMAGE_DIR: /data/images
    volumes:
      - "models-data:/data/models"
      - "images-data:/data/images"
    ports:
      - 9090:9090

  labelstudio:
    image: heartexlabs/label-studio
    command:
      - label-studio
      - start
      - --init
      - --template
      - image_classification
      - --ml-backend-url
      - http://server:9090
      - --ml-backend-name
      - fastai_classifier
      - labeling_project

    ports:
      # <HOST_PORT:CONTAINER_PORT>
      - 8280:8080
